---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
---
kind: pipeline
name: build
steps:
- commands:
  - apk add make
  - make build
  image: docker:20-git
  name: build
  volumes:
  - name: docker
    path: /var/run/docker.sock
- commands:
  - apk add make
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  image: docker:20-git
  name: push
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master
    - main
    event:
    - push
trigger:
  branch:
  - master
  - main
  event:
  - push
  - pull_request
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: signature
hmac: 0e23797d5e26243e1fcd248dcf0f6881f64829a2b0e61b09e7eada2cd34d3f11

...
