name: Publish grafana/fake-data-gen image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository == 'grafana/fake-data-gen' }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - id: push-to-dockerhub
        uses: grafana/shared-workflows/actions/docker-build-push-image@21ae57f82e5256e5a418406388926d4ba24bccf2 # docker-build-push-image/v0.3.2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          dockerhub-repository: grafana/fake-data-gen
          registries: dockerhub
          tags: |-
            ${{ github.sha }}
            latest
